spring:
  application:
    name: discovery
  cloud:
    config:
      uri: http://localhost:8081
      name: discovery

---

spring:
  profiles: dev

  datasource:
    url: localhost-test1
    name: dev011

---

spring:
  profiles: prod

  datasource:
    url: localhost-prod
    name: prod01